### ISSUE TITLE
Setup deploy pipeline

### ISSUE THREAD

**Issue by mrjkey** [Tris20/FairFareFinder#10]
The repo could use a way to automatically deploy if all tests pass.

- [x] Create some tests
- [x] Setup build and test pipeline with GitHub actions
- [x] setup hook to trigger production server to get the latest updates.

**Comment by mrjkey** [comment]
@Tris20 no try again with reference

**Comment by mrjkey** [comment]
@bneenb you now

**Comment by Tris20** [comment]
@mrjkey hello world
